import type { Metadata } from "next";
import { Roboto } from "next/font/google";

// using font families in nextjs
const inter = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} container`}>{children}</body>
    </html>
  );
}
