import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Header from "./components/header";
import Footer from "./components/footer";

// using font families in nextjs
const inter = Roboto({
  weight: ["100", "300", "400", "500", "700"],
  style: ["italic", "normal"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pagination App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(children);
  return (
    <html lang="en">
      <body className={`${inter.className} container`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
